[server]
headless = true
port = 8501

[theme]
primaryColor = "#FDB515"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#003262"
font = "sans serif"

[browser]
gatherUsageStats = false